OPENRESTY_PREFIX=/usr/local/openresty-debug
TEST_LEDGE_REDIS_DATABASE=1
TEST_FILE ?= t

TEST_LEDGE_SENTINEL_PORT ?= 26379
TEST_LEDGE_SENTINEL_MASTER_NAME ?= mymaster
TEST_LEDGE_SENTINEL_PROMOTION_TIME ?= 20

PREFIX ?=          /usr/local
LUA_INCLUDE_DIR ?= $(PREFIX)/include
LUA_LIB_DIR ?=     $(PREFIX)/lib/lua/$(LUA_VERSION)
INSTALL ?= install

.PHONY: all test install

all: ;

install: all
	$(INSTALL) -d $(DESTDIR)/$(LUA_LIB_DIR)/ledge
	$(INSTALL) lib/ledge/*.lua $(DESTDIR)/$(LUA_LIB_DIR)/ledge

test: all
	redis-cli -n $(TEST_LEDGE_REDIS_DATABASE) flushdb
	PATH=$(OPENRESTY_PREFIX)/nginx/sbin:$$PATH TEST_LEDGE_REDIS_DATABASE=$(TEST_LEDGE_REDIS_DATABASE) TEST_NGINX_NO_SHUFFLE=1 prove -I../test-nginx/lib	$(TEST_FILE)

test_sentinel: all
	PATH=$(OPENRESTY_PREFIX)/nginx/sbin:$$PATH TEST_LEDGE_SENTINEL_PORT=$(TEST_LEDGE_SENTINEL_PORT) TEST_LEDGE_SENTINEL_MASTER_NAME=$(TEST_LEDGE_SENTINEL_MASTER_NAME) TEST_LEDGE_REDIS_DATABASE=$(TEST_LEDGE_REDIS_DATABASE) TEST_NGINX_NO_SHUFFLE=1 prove -I../test-nginx/lib t/sentinel/01-master_up.t
	redis-cli shutdown
	PATH=$(OPENRESTY_PREFIX)/nginx/sbin:$$PATH TEST_LEDGE_SENTINEL_PORT=$(TEST_LEDGE_SENTINEL_PORT) TEST_LEDGE_SENTINEL_MASTER_NAME=$(TEST_LEDGE_SENTINEL_MASTER_NAME) TEST_LEDGE_REDIS_DATABASE=$(TEST_LEDGE_REDIS_DATABASE) TEST_NGINX_NO_SHUFFLE=1 prove -I../test-nginx/lib t/sentinel/02-master_down.t
	sleep $(TEST_LEDGE_SENTINEL_PROMOTION_TIME)
	PATH=$(OPENRESTY_PREFIX)/nginx/sbin:$$PATH TEST_LEDGE_SENTINEL_PORT=$(TEST_LEDGE_SENTINEL_PORT) TEST_LEDGE_SENTINEL_MASTER_NAME=$(TEST_LEDGE_SENTINEL_MASTER_NAME) TEST_LEDGE_REDIS_DATABASE=$(TEST_LEDGE_REDIS_DATABASE) TEST_NGINX_NO_SHUFFLE=1 prove -I../test-nginx/lib t/sentinel/03-slave_promoted.t

